apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argo-cd
    meta.helm.sh/release-namespace: cicd
  labels:
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argo-cd
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: 2.11.0
    helm.sh/chart: argo-cd-6.2.1
  name: argocd-rbac-cm
  namespace: cicd
data:
  policy.csv: |
    g, argo-account, role:admin